Update file.yml

diff --git a/.github/workflows/file.yml b/.github/workflows/file.yml
--- a/.github/workflows/file.yml
+++ b/.github/workflows/file.yml
@@ -64,10 +64,10 @@ jobs:
           status_check=$(aws dynamodb execute-statement --statement "SELECT status FROM execution_status WHERE pipelineExecutionArn='arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa'" | jq '.Items[0] .status .S')
           echo $status_check
           if [ "$status_check" == "Succeeded" ]; then
-             echo "🎉🎉Sagemaker Pipeline completed successfully 🚀🚀"
+              echo "🎉🎉Sagemaker Pipeline completed successfully 🚀🚀"
           else
-             echo "Sagemaker pipleline failing with status: $status_check 🐧"
-             exit 1
+              echo "Sagemaker pipleline failing with status: $status_check 🐧"
+              exit 1
           fi
         fi
         
