Update file.yml

diff --git a/.github/workflows/file.yml b/.github/workflows/file.yml
--- a/.github/workflows/file.yml
+++ b/.github/workflows/file.yml
@@ -55,8 +55,14 @@ jobs:
     - uses: actions/checkout@v2
     - name: check_on_Dynamodb
       run: |
-        "value=$(aws dynamodb execute-statement --statement "SELECT * FROM execution_status WHERE pipelineExecutionArn='${{ needs.get_pipeline_arn.outputs.arn }}'")"
-        if [ "${#value[@]}" == 0 ]
-        then
-           aws dynamodb execute-statement --statement "UPDATE execution_status SET pipelineExecutionArn='${{ needs.get_pipeline_arn.outputs.arn }}' SET github_runid='${{ github.run_id }}'"
+        "value=$(aws dynamodb execute-statement --statement "SELECT pipelineExecutionArn FROM execution_status WHERE pipelineExecutionArn='arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa'")"
+        if [[ -z "$value" ]] then
+           aws dynamodb execute-statement --statement "UPDATE execution_status SET pipelineExecutionArn='arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa' SET github_runid='${{ github.run_id }}'"
+        else
+          "status_check=$(aws dynamodb execute-statement --statement "SELECT status FROM execution_status WHERE pipelineExecutionArn='arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa'")";
+          if [[ $status_check == "Succeeded" ]]; then
+            echo "Pipeline ran successfully";
+          else
+            echo "Pipeline failed to fetch the status"
+            exit 1   
         
