Update file.yml

diff --git a/.github/workflows/file.yml b/.github/workflows/file.yml
--- a/.github/workflows/file.yml
+++ b/.github/workflows/file.yml
@@ -55,19 +55,19 @@ jobs:
     - uses: actions/checkout@v2
     - name: check_on_Dynamodb
       run: |
-         value=$(aws dynamodb execute-statement --statement "SELECT pipelineExecutionArn FROM execution_status WHERE pipelineExecutionArn='arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa'"| jq '.Items[0] .pipelineExecutionArn .S')
-         echo $value
-         if [ $value == "null" ]; then
-            aws dynamodb execute-statement --statement "INSERT INTO execution_status VALUE {'pipelineExecutionArn':'arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa','github_runid':'${{ github.run_id }}'}"
+        value=$(aws dynamodb execute-statement --statement "SELECT pipelineExecutionArn FROM execution_status WHERE pipelineExecutionArn='arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa'"| jq '.Items[0] .pipelineExecutionArn .S')
+        echo $value
+        if [ $value == "null" ]; then
+          aws dynamodb execute-statement --statement "INSERT INTO execution_status VALUE {'pipelineExecutionArn':'arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa','github_runid':'${{ github.run_id }}'}"
+          exit 1
+        else
+          status_check=$(aws dynamodb execute-statement --statement "SELECT status FROM execution_status WHERE pipelineExecutionArn='arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa'" | jq '.Items[0] .status .S')
+          echo $status_check
+          if [ $status_check == "Succeeded" ]; then
+            echo "🎉🎉Sagemaker Pipeline completed successfully 🚀🚀"
+          else
+            echo "Sagemaker pipleline failing with status: $status_check 🐧"
             exit 1
-         else
-            status_check=$(aws dynamodb execute-statement --statement "SELECT status FROM execution_status WHERE pipelineExecutionArn='arn:aws:sagemaker:us-west-2:858958072653:pipeline/abalonepipeline/execution/er1qkmpvq7wa'" | jq '.Items[0] .status .S')
-            echo $status_check
-            if [ $status_check == "Succeeded" ]; then
-               echo "🎉🎉Sagemaker Pipeline completed successfully 🚀🚀"
-            else
-               echo "Sagemaker pipleline failing with status: $status_check 🐧"
-               exit 1
-            fi
-         fi
+          fi
+        fi
         
